import { createElement } from 'lwc';
import Lwc_wire_from_basic15 from 'c/lwc_wire_from_basic15';

describe('c-lwc-wire-from-basic15', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-wire-from-basic15', {
            is: Lwc_wire_from_basic15
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});