import { createElement } from 'lwc';
import Recordform_using_customfield12 from 'c/recordform_using_customfield12';

describe('c-recordform-using-customfield12', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-recordform-using-customfield12', {
            is: Recordform_using_customfield12
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});